# Translations template for ironic.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 2015.1.dev31\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-18 06:15+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/middleware/parsable_error.py:81
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ironic/common/exception.py:79
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/images.py:132
#, python-format
msgid "vfat image creation failed. Error: %s"
msgstr ""

#: ironic/common/images.py:200
msgid "Creating the filesystem root failed."
msgstr ""

#: ironic/common/images.py:214
msgid "Creating ISO image failed."
msgstr ""

#: ironic/common/service.py:89
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:94
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:398
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/utils.py:429
#, python-format
msgid "Failed to make file system. File system %s is not supported."
msgstr ""

#: ironic/common/utils.py:433
#, python-format
msgid "Failed to create a file system in %(path)s. Error: %(error)s"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:127
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"attempt %(attempt)s of %(num_attempts)s failed."
msgstr ""

#: ironic/conductor/manager.py:224
#, python-format
msgid ""
"Conductor %s cannot be started because no drivers were loaded.  This "
"could be because no drivers were specified in 'enabled_drivers' config "
"option."
msgstr ""

#: ironic/conductor/manager.py:1029
#, python-format
msgid "Failed to stop console while deleting the node %(node)s: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:1510
#, python-format
msgid "Unexpected state %(state)s returned while deploying node %(node)s."
msgstr ""

#: ironic/conductor/manager.py:1637
#, python-format
msgid ""
"Failed to change power state of node %(node)s to '%(state)s'. Attempts "
"left: %(left)s."
msgstr ""

#: ironic/dhcp/neutron.py:124
#, python-format
msgid "Failed to update Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:139
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:206
#, python-format
msgid "Failed to Get IP address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:222
#, python-format
msgid "Neutron returned invalid IPv4 address %s."
msgstr ""

#: ironic/dhcp/neutron.py:226
#, python-format
msgid "No IP address assigned to Neutron port %s."
msgstr ""

#: ironic/drivers/base.py:407
#, python-format
msgid "vendor_passthru failed with method %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:168
#, python-format
msgid "Async exception for %(node)s: %(msg)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:282
#, python-format
msgid "Could not find matching node for the provided MACs %s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:354
#, python-format
msgid ""
"Failed to erase beginning of disk for node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:366
#, python-format
msgid ""
"Failed to get disk block count for node %(node)s. Command: %(command)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:379
#, python-format
msgid ""
"Failed to erase the end of the disk on node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:530
msgid "Failed to detect root device UUID."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:572
#: ironic/drivers/modules/deploy_utils.py:578
#, python-format
msgid "Deploy to address %s failed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:573
#, python-format
msgid "Command: %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:574
#, python-format
msgid "StdOut: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:575
#, python-format
msgid "StdErr: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:659
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."
msgstr ""

#: ironic/drivers/modules/ipminative.py:263
#, python-format
msgid ""
"IPMI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:414
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:449
#, python-format
msgid ""
"IPMI get boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:413
#, python-format
msgid ""
"IPMI power %(state)s timed out after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:573
#, python-format
msgid "IPMI \"raw bytes\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:879
#, python-format
msgid "IPMI \"bmc reset\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:266
#, python-format
msgid "Error returned from deploy ramdisk: %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:279 ironic/drivers/modules/pxe.py:515
#: ironic/drivers/modules/ilo/deploy.py:525
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:328
msgid "UEFI boot mode is not supported with iPXE boot enabled."
msgstr ""

#: ironic/drivers/modules/seamicro.py:197
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:478
#: ironic/drivers/modules/seamicro.py:517
#, python-format
msgid "SeaMicro client exception: %s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:580
#, python-format
msgid ""
"Seamicro set boot device failed for node %(node)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ssh.py:268
#, python-format
msgid "Cannot execute SSH cmd %(cmd)s. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/ssh.py:369
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:653
#, python-format
msgid ""
"Failed to set boot device for node %(node)s, virt_type %(vtype)s does not"
" support this operation"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:160
#, python-format
msgid ""
"Failed while creating a VirtualMachine object for node %(node)s. Error: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:176
#, python-format
msgid "'%(ironic_method)s' failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:218
#, python-format
msgid "VirtualBox returned unknown state '%(state)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:313
#, python-format
msgid "VirtualBox returned unknown boot device '%(device)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:354
#, python-format
msgid "'set_boot_device' failed for node %(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/drac/management.py:82
#, python-format
msgid ""
"DRAC driver failed to get next boot mode for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:134
#, python-format
msgid ""
"DRAC driver failed to create config job for node %(node_uuid)s. The "
"changes are not applied. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:153
#, python-format
msgid ""
"DRAC driver failed to list the configuration jobs for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:239
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s. Can't "
"find the ID for the %(device)s type. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:264
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s to "
"%(target_boot_device)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:303
#, python-format
msgid ""
"DRAC driver failed to get the current boot device for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:61
#, python-format
msgid ""
"DRAC driver failed to get power state for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:89
#, python-format
msgid ""
"DRAC driver failed to set power state for node %(node_uuid)s to "
"%(target_power_state)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:412
#, python-format
msgid "Error while deleting %(object_name)s from %(container)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:422
#, python-format
msgid ""
"Error while ejecting virtual media %(device)s from node %(uuid)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:109
#, python-format
msgid ""
"Unable to find boot_iso in Glance, required to deploy node %(node)s in "
"UEFI boot mode."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:115
#, python-format
msgid ""
"Unable to find 'kernel_id' and 'ramdisk_id' in Glance image %(image)s for"
" generating boot ISO for %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:156
#, python-format
msgid "Failed to clean up boot ISO for %(node)s.Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:509
#, python-format
msgid "Cannot get boot ISO for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:85
#, python-format
msgid "iLO get_power_state failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/power.py:157
#, python-format
msgid ""
"iLO set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:170
#, python-format
msgid "iLO failed to change state to %(tstate)s within %(timeout)s sec"
msgstr ""

#: ironic/drivers/modules/irmc/power.py:65
#, python-format
msgid ""
"iRMC set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/objects/base.py:71
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: ironic/objects/base.py:223
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: ironic/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: ironic/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: ironic/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: ironic/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: ironic/openstack/common/periodic_task.py:228
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: ironic/openstack/common/policy.py:563 ironic/openstack/common/policy.py:843
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: ironic/openstack/common/policy.py:573
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: ironic/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr ""

#: ironic/tests/db/sqlalchemy/test_migrations.py:174
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr ""

