# Translations template for ironic.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 2015.1.dev1.gb90f423\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-20 11:51+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/middleware/parsable_error.py:81
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ironic/common/exception.py:79
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/images.py:148
#, python-format
msgid "vfat image creation failed. Error: %s"
msgstr ""

#: ironic/common/images.py:218 ironic/common/images.py:284
msgid "Creating the filesystem root failed."
msgstr ""

#: ironic/common/images.py:233 ironic/common/images.py:310
msgid "Creating ISO image failed."
msgstr ""

#: ironic/common/images.py:540
msgid "mounting the deploy iso failed."
msgstr ""

#: ironic/common/images.py:554
msgid "examining the deploy iso failed."
msgstr ""

#: ironic/common/service.py:92
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:97
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:401
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/utils.py:432
#, python-format
msgid "Failed to make file system. File system %s is not supported."
msgstr ""

#: ironic/common/utils.py:436
#, python-format
msgid "Failed to create a file system in %(path)s. Error: %(error)s"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:128
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"attempt %(attempt)s of %(num_attempts)s failed."
msgstr ""

#: ironic/conductor/manager.py:256
#, python-format
msgid ""
"Conductor %s cannot be started because no drivers were loaded.  This "
"could be because no drivers were specified in 'enabled_drivers' config "
"option."
msgstr ""

#: ironic/conductor/manager.py:799
#, python-format
msgid "Error in tear_down of node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:1280
#, python-format
msgid "Failed to stop console while deleting the node %(node)s: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:1907
#, python-format
msgid "Unexpected state %(state)s returned while deploying node %(node)s."
msgstr ""

#: ironic/conductor/manager.py:2007
#, python-format
msgid ""
"Failed to change power state of node %(node)s to '%(state)s'. Attempts "
"left: %(left)s."
msgstr ""

#: ironic/conductor/manager.py:2039
#, python-format
msgid "Failed to inspect node %(node)s: %(err)s"
msgstr ""

#: ironic/dhcp/neutron.py:128
#, python-format
msgid "Failed to update Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:143
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:216
#, python-format
msgid "Failed to Get IP address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:232
#, python-format
msgid "Neutron returned invalid IPv4 address %s."
msgstr ""

#: ironic/dhcp/neutron.py:236
#, python-format
msgid "No IP address assigned to Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:379
#, python-format
msgid "Failed to rollback cleaning port changes for node %s"
msgstr ""

#: ironic/drivers/base.py:511
#, python-format
msgid "vendor_passthru failed with method %s"
msgstr ""

#: ironic/drivers/modules/agent.py:195
#, python-format
msgid ""
"Agent deploy supports only HTTP(S) URLs as instance_info['image_source']."
" Either %s is not a valid HTTP(S) URL or is not reachable."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:374
#, python-format
msgid "Could not find matching node for the provided MACs %s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:449
#, python-format
msgid ""
"Failed to erase beginning of disk for node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:461
#, python-format
msgid ""
"Failed to get disk block count for node %(node)s. Command: %(command)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:474
#, python-format
msgid ""
"Failed to erase the end of the disk on node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:646
#, python-format
msgid "Failed to detect %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:741
#: ironic/drivers/modules/deploy_utils.py:747
#, python-format
msgid "Deploy to address %s failed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:742
#, python-format
msgid "Command: %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:743
#, python-format
msgid "StdOut: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:744
#, python-format
msgid "StdErr: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:832
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."
msgstr ""

#: ironic/drivers/modules/discoverd.py:160
#, python-format
msgid ""
"Exception during contacting ironic-discoverd for inspection of node "
"%(node)s: %(err)s"
msgstr ""

#: ironic/drivers/modules/discoverd.py:191
#, python-format
msgid ""
"Unexpected exception while getting inspection status for node %s, will "
"retry later"
msgstr ""

#: ironic/drivers/modules/discoverd.py:197
#, python-format
msgid "Inspection failed for node %(uuid)s with error: %(err)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:268
#, python-format
msgid ""
"IPMI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:419
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:454
#, python-format
msgid ""
"IPMI get boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:387
#, python-format
msgid ""
"IPMI Error while attempting \"%(cmd)s\" for node %(node)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:467
#, python-format
msgid ""
"IPMI power %(state)s timed out after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:627
#, python-format
msgid "IPMI \"raw bytes\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:933
#, python-format
msgid "IPMI \"bmc reset\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:617 ironic/drivers/modules/pxe.py:635
#: ironic/drivers/modules/ilo/deploy.py:832
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:250
msgid "Whole disk image with netboot is not supported in UEFI boot mode."
msgstr ""

#: ironic/drivers/modules/pxe.py:365
msgid "UEFI boot mode is not supported with iPXE boot enabled."
msgstr ""

#: ironic/drivers/modules/seamicro.py:197
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:478
#: ironic/drivers/modules/seamicro.py:517
#, python-format
msgid "SeaMicro client exception: %s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:580
#, python-format
msgid ""
"Seamicro set boot device failed for node %(node)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ssh.py:268
#, python-format
msgid "Cannot execute SSH cmd %(cmd)s. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/ssh.py:369
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:653
#, python-format
msgid ""
"Failed to set boot device for node %(node)s, virt_type %(vtype)s does not"
" support this operation"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:160
#, python-format
msgid ""
"Failed while creating a VirtualMachine object for node %(node_id)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:176
#, python-format
msgid "'%(ironic_method)s' failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:218
#, python-format
msgid "VirtualBox returned unknown state '%(state)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:313
#, python-format
msgid "VirtualBox returned unknown boot device '%(device)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:354
#, python-format
msgid "'set_boot_device' failed for node %(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/amt/common.py:105
#, python-format
msgid "Call to AMT with URI %(uri)s failed: got Fault %(fault)s"
msgstr ""

#: ironic/drivers/modules/amt/common.py:129
#, python-format
msgid ""
"Call to AMT with URI %(uri)s and method %(method)s failed: return value "
"was %(value)s"
msgstr ""

#: ironic/drivers/modules/amt/management.py:62
#, python-format
msgid ""
"Failed to set boot device %(boot_device)s for node %(node_id)s with "
"error: %(error)s."
msgstr ""

#: ironic/drivers/modules/amt/management.py:95
#, python-format
msgid "Failed to enable boot config for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:112
#, python-format
msgid ""
"Failed to set power state %(state)s for node %(node_id)s with error: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:136
#, python-format
msgid "Failed to get power state for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:82
#, python-format
msgid ""
"DRAC driver failed to get next boot mode for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:134
#, python-format
msgid ""
"DRAC driver failed to create config job for node %(node_uuid)s. The "
"changes are not applied. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:153
#, python-format
msgid ""
"DRAC driver failed to list the configuration jobs for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:239
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s. Can't "
"find the ID for the %(device)s type. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:264
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s to "
"%(target_boot_device)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:303
#, python-format
msgid ""
"DRAC driver failed to get the current boot device for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:61
#, python-format
msgid ""
"DRAC driver failed to get power state for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:89
#, python-format
msgid ""
"DRAC driver failed to set power state for node %(node_uuid)s to "
"%(target_power_state)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:450
#, python-format
msgid "Error while deleting %(object_name)s from %(container)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:460
#, python-format
msgid ""
"Error while ejecting virtual media %(device)s from node %(uuid)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:122
#, python-format
msgid ""
"Virtual media deploy accepts only Glance images or HTTP(S) URLs as "
"instance_info['ilo_boot_iso']. Either %s is not a valid HTTP(S) URL or is"
" not reachable."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:149
#, python-format
msgid ""
"Unable to find kernel or ramdisk for image %(image)s to generate boot ISO"
" for %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:197
#, python-format
msgid "Failed to clean up boot ISO for %(node)s.Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:740
#, python-format
msgid "Cannot get boot ISO for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:92
#, python-format
msgid "iLO get_power_state failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/power.py:164
#, python-format
msgid ""
"iLO set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:177
#, python-format
msgid "iLO failed to change state to %(tstate)s within %(timeout)s sec"
msgstr ""

#: ironic/drivers/modules/irmc/management.py:60
#, python-format
msgid ""
"SCCI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/power.py:65
#, python-format
msgid ""
"iRMC set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/objects/base.py:71
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: ironic/objects/base.py:223
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: ironic/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: ironic/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: ironic/openstack/common/periodic_task.py:228
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: ironic/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr ""

#: ironic/tests/db/sqlalchemy/test_migrations.py:168
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr ""

